### ISSUE TITLE
Bug client can not connect: SocketException: No route to host (OS Error: No route to host, errno = 113)

### ISSUE THREAD

**Issue by huynguyennovem** [huynguyennovem/netshare#65]
```console
E/flutter (  647): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: No route to host (OS Error: No route to host, errno = 113)
E/flutter (  647): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:719:35)
E/flutter (  647): #1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:982:12)
E/flutter (  647): #2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1865:26)
E/flutter (  647): #3      RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)
E/flutter (  647): #4      Socket._connect (dart:io-patch/socket_patch.dart:2090:22)
E/flutter (  647): #5      Socket.connect (dart:io/socket.dart:750:21)
E/flutter (  647): #6      _ConnectWidgetState._onClickConnect (package:netshare/ui/client/connect_widget.dart:140:35)
E/flutter (  647): #7      _ConnectWidgetState._buildMainLayout.<anonymous closure> (package:netshare/ui/client/connect_widget.dart:94:36)
E/flutter (  647): #8      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
E/flutter (  647): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
E/flutter (  647): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
E/flutter (  647): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
E/flutter (  647): #12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:281:7)
E/flutter (  647): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
E/flutter (  647): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:469:20)
E/flutter (  647): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:445:22)
E/flutter (  647): #16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:331:11)
E/flutter (  647): #17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:400:7)
E/flutter (  647): #18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:363:5)
E/flutter (  647): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:320:7)
E/flutter (  647): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:293:9)
E/flutter (  647): #21     _invoke1 (dart:ui/hooks.dart:186:13)
E/flutter (  647): #22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:423:7)
E/flutter (  647): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)
E/flutter (  647): 
```

**Comment by huynguyennovem** [comment]
Caused by router's issue. After changing another one, it works as expected. Closing

**Comment by huynguyennovem** [comment]
Caused by using diff network router. After using the same router for both client and server, it works as expected
